environment:
  matrix:
     - GENERATOR: "Visual Studio 15 2017"
       CONFIG: Release

matrix:
  fast_finish: true

build_script:
  - mkdir build
  - cd build
  - cd build && cmake ..
  - cmake --build . --config Release
