version: 1.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu1804
build:
  verbosity: minimal

build_script:
  - git submodule update --init --recursive
  - cmake --version
  - python3 utils.py build
