version: 1.0.{build}
image:
  - Visual Studio 2019
build:
  verbosity: minimal

environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"

build_script:
  - git submodule update --init --recursive
  - cmake --version
  - "%PYTHON%\\python.exe utils.py build"
