language: cpp
compiler: clang

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      addons:
        apt:
          sources:
          packages:
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
      env:
        - BUILD_SHARED_LIBS=OFF
        - CFLAGS=-Werror

script:
  - cmake --version
  - mkdir build
  - cd build && cmake ..
  - cmake --build . --config Release
