language: cpp
sudo: required
common_sources: &1
  - ubuntu-toolchain-r-test
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources: *1
          packages:
            - g++-7
            - libxrandr-dev
            - libxinerama-dev
            - libxcursor-dev
            - libxi-dev
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"
  - echo $CXX

script:
  - cmake --version
  - mkdir build && cd build && cmake .. && cmake --build . --config Release
